### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by caarlos0** [thoas/stats#18]
Seems like @thoas never commented or did anything in this project since april.

Is it abandoned?

If yes, I'll continue it in my fork (https://github.com/caarlos0/stats)...

**Comment by thoas** [comment]
It's not abandoned :)

**Comment by caarlos0** [comment]
@thoas Nice =D

**Comment by caarlos0** [comment]
@thoas BTW, any plans for make it work with [fasthttp](https://github.com/valyala/fasthttp)?
