### ISSUE TITLE
*Options has no field or method saveResult

### ISSUE THREAD

**Issue by artpar** [thoas/stats#35]
```golang
// Options are stats options.
type Options struct {
	statusCode *int
	size       int
	recorder   ResponseWriter
}
```

https://github.com/thoas/stats/blob/ec540afe6231778704c45afd1fd907089d650de7/options.go#L55

`../../thoas/stats/options.go:55:4: o.saveResult undefined (type *Options has no field or method saveResult)`

**Comment by thoas** [comment]
it should be fixed, thank you for the report.
